# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=oasis
      - MARIADB_PASSWORD=oasis
  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=user
      - DB_DATABASE=oasis
      - DB_PASSWORD=oasis
    volumes:
      - './oasis:/app'
    depends_on:
      - mariadb
